-- MySQL Script generated by MySQL Workbench
-- 12/12/16 22:52:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema quanlybanlaptop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema quanlybanlaptop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quanlybanlaptop` DEFAULT CHARACTER SET utf8 ;
USE `quanlybanlaptop` ;

-- -----------------------------------------------------
-- Table `quanlybanlaptop`.`taikhoan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlybanlaptop`.`taikhoan` (
  `Ho` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  `Ten` VARCHAR(10) CHARACTER SET 'utf8' NOT NULL,
  `TaiKhoan` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  `MatKhau` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  `Email` VARCHAR(20) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `SDT` VARCHAR(11) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `GioiTinh` VARCHAR(10) CHARACTER SET 'utf8' NOT NULL,
  `NgaySinh` DATE NULL DEFAULT NULL,
  `NgayDK` DATE NULL DEFAULT NULL,
  `LoaiTK` VARCHAR(10) CHARACTER SET 'utf8' NOT NULL,
  `DiaChi` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`TaiKhoan`),
  UNIQUE INDEX `Email` (`Email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `quanlybanlaptop`.`nhanvien`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlybanlaptop`.`nhanvien` (
  `MaNV` VARCHAR(30) NOT NULL,
  `HoNV` VARCHAR(20) NULL DEFAULT NULL,
  `TenNV` VARCHAR(10) NULL DEFAULT NULL,
  `TaiKhoan` VARCHAR(20) NULL DEFAULT NULL,
  `DiaChi` VARCHAR(50) NULL DEFAULT NULL,
  `SDT` DECIMAL(11,0) NULL DEFAULT NULL,
  `CongViec` VARCHAR(20) NULL DEFAULT NULL,
  `NgayVaoLam` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`MaNV`),
  INDEX `FK_20` (`TaiKhoan` ASC),
  CONSTRAINT `FK_20`
    FOREIGN KEY (`TaiKhoan`)
    REFERENCES `quanlybanlaptop`.`taikhoan` (`TaiKhoan`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `quanlybanlaptop`.`nhapp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlybanlaptop`.`nhapp` (
  `TenNhaPP` VARCHAR(20) NOT NULL,
  `DiaChi` VARCHAR(50) NOT NULL,
  `SDT` VARCHAR(12) NULL DEFAULT NULL,
  PRIMARY KEY (`TenNhaPP`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `quanlybanlaptop`.`kho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlybanlaptop`.`kho` (
  `MaKho` VARCHAR(10) NOT NULL,
  `ViTri` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`MaKho`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `quanlybanlaptop`.`mathang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlybanlaptop`.`mathang` (
  `MaHang` VARCHAR(30) NOT NULL,
  `TenHang` VARCHAR(30) NOT NULL,
  `Chip` VARCHAR(50) NULL DEFAULT NULL,
  `Xung` VARCHAR(10) NULL DEFAULT NULL,
  `OCung` VARCHAR(10) NULL DEFAULT NULL,
  `RAM` VARCHAR(50) NULL DEFAULT NULL,
  `VGA` VARCHAR(50) NULL DEFAULT NULL,
  `Cache` VARCHAR(10) NULL DEFAULT NULL,
  `ThoiGianBH` VARCHAR(10) NULL DEFAULT NULL,
  `DonGia` DECIMAL(10,0) NULL DEFAULT NULL,
  `SoLuong` INT(11) NULL DEFAULT NULL,
  `NhaPP` VARCHAR(20) NULL DEFAULT NULL,
  `MaKho` VARCHAR(10) NULL DEFAULT NULL,
  `Image` VARCHAR(300) NULL DEFAULT NULL,
  PRIMARY KEY (`MaHang`),
  INDEX `FK_1` (`NhaPP` ASC),
  INDEX `FK_2` (`MaKho` ASC),
  CONSTRAINT `FK_1`
    FOREIGN KEY (`NhaPP`)
    REFERENCES `quanlybanlaptop`.`nhapp` (`TenNhaPP`),
  CONSTRAINT `FK_2`
    FOREIGN KEY (`MaKho`)
    REFERENCES `quanlybanlaptop`.`kho` (`MaKho`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `quanlybanlaptop`.`khachhang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlybanlaptop`.`khachhang` (
  `MaKH` VARCHAR(30) NOT NULL,
  `HoKH` VARCHAR(20) NULL DEFAULT NULL,
  `TenKH` VARCHAR(10) NULL DEFAULT NULL,
  `TaiKhoan` VARCHAR(20) NULL DEFAULT NULL,
  `SDT` DECIMAL(10,0) NULL DEFAULT NULL,
  `DiaChi` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`MaKH`),
  INDEX `FK_5` (`TaiKhoan` ASC),
  CONSTRAINT `FK_5`
    FOREIGN KEY (`TaiKhoan`)
    REFERENCES `quanlybanlaptop`.`taikhoan` (`TaiKhoan`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `quanlybanlaptop`.`baohanh`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlybanlaptop`.`baohanh` (
  `MaPhieu` VARCHAR(10) NOT NULL,
  `MaKH` VARCHAR(30) NULL DEFAULT NULL,
  `MaNV` VARCHAR(30) NULL DEFAULT NULL,
  `MaHang` VARCHAR(30) NULL DEFAULT NULL,
  `NgayNhanMay` DATE NULL DEFAULT NULL,
  `NgayTraMay` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`MaPhieu`),
  INDEX `FK_15` (`MaKH` ASC),
  INDEX `FK_13` (`MaNV` ASC),
  INDEX `FK_14` (`MaHang` ASC),
  CONSTRAINT `FK_13`
    FOREIGN KEY (`MaNV`)
    REFERENCES `quanlybanlaptop`.`nhanvien` (`MaNV`),
  CONSTRAINT `FK_14`
    FOREIGN KEY (`MaHang`)
    REFERENCES `quanlybanlaptop`.`mathang` (`MaHang`),
  CONSTRAINT `FK_15`
    FOREIGN KEY (`MaKH`)
    REFERENCES `quanlybanlaptop`.`khachhang` (`MaKH`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `quanlybanlaptop`.`hoadon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlybanlaptop`.`hoadon` (
  `MaHD` VARCHAR(30) NOT NULL,
  `NgayLap` DATE NULL DEFAULT NULL,
  `MaKH` VARCHAR(30) NULL DEFAULT NULL,
  `MaNV` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`MaHD`),
  INDEX `FK_6` (`MaKH` ASC),
  INDEX `FK_10` (`MaNV` ASC),
  CONSTRAINT `FK_10`
    FOREIGN KEY (`MaNV`)
    REFERENCES `quanlybanlaptop`.`nhanvien` (`MaNV`),
  CONSTRAINT `FK_6`
    FOREIGN KEY (`MaKH`)
    REFERENCES `quanlybanlaptop`.`khachhang` (`MaKH`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `quanlybanlaptop`.`cthoadon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlybanlaptop`.`cthoadon` (
  `MaHD` VARCHAR(30) NOT NULL,
  `MaHang` VARCHAR(30) NOT NULL,
  `DonGia` DECIMAL(10,0) NULL DEFAULT NULL,
  `SoLuong` DECIMAL(10,0) NULL DEFAULT NULL,
  `ThanhTien` DECIMAL(10,0) NULL DEFAULT NULL,
  PRIMARY KEY (`MaHD`, `MaHang`),
  INDEX `FK_22` (`MaHang` ASC),
  CONSTRAINT `FK_21`
    FOREIGN KEY (`MaHD`)
    REFERENCES `quanlybanlaptop`.`hoadon` (`MaHD`),
  CONSTRAINT `FK_22`
    FOREIGN KEY (`MaHang`)
    REFERENCES `quanlybanlaptop`.`mathang` (`MaHang`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `quanlybanlaptop`.`phieunhap`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlybanlaptop`.`phieunhap` (
  `SoPhieu` VARCHAR(30) NOT NULL,
  `NgayNhap` DATE NULL DEFAULT NULL,
  `LyDoNhap` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`SoPhieu`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `quanlybanlaptop`.`ctphieunhap`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlybanlaptop`.`ctphieunhap` (
  `SoPhieu` VARCHAR(30) NOT NULL,
  `MaHang` VARCHAR(30) NOT NULL,
  `SoLuongNhap` INT(11) NULL DEFAULT NULL,
  `DonGia` DECIMAL(10,0) NULL DEFAULT NULL,
  PRIMARY KEY (`SoPhieu`, `MaHang`),
  INDEX `FK_MH_HN` (`MaHang` ASC),
  CONSTRAINT `FK_MH_HN`
    FOREIGN KEY (`MaHang`)
    REFERENCES `quanlybanlaptop`.`mathang` (`MaHang`),
  CONSTRAINT `FK_PN_HN`
    FOREIGN KEY (`SoPhieu`)
    REFERENCES `quanlybanlaptop`.`phieunhap` (`SoPhieu`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `quanlybanlaptop`.`giohang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlybanlaptop`.`giohang` (
  `TaiKhoan` VARCHAR(20) NOT NULL,
  `Email` VARCHAR(20) NULL DEFAULT NULL,
  `SDT` DECIMAL(11,0) NULL DEFAULT NULL,
  `DiaChi` VARCHAR(50) NULL DEFAULT NULL,
  `MaHang` VARCHAR(30) NOT NULL,
  `SoLuong` INT(11) NULL DEFAULT NULL,
  `NgayMua` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`TaiKhoan`, `MaHang`),
  INDEX `MaHang` (`MaHang` ASC),
  CONSTRAINT `giohang_ibfk_1`
    FOREIGN KEY (`MaHang`)
    REFERENCES `quanlybanlaptop`.`mathang` (`MaHang`),
  CONSTRAINT `giohang_ibfk_2`
    FOREIGN KEY (`TaiKhoan`)
    REFERENCES `quanlybanlaptop`.`taikhoan` (`TaiKhoan`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `quanlybanlaptop`.`gopy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlybanlaptop`.`gopy` (
  `TaiKhoan` VARCHAR(20) NOT NULL,
  `SDT` DECIMAL(11,0) NULL DEFAULT NULL,
  `Email` VARCHAR(20) NULL DEFAULT NULL,
  `NoiDung` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`TaiKhoan`),
  CONSTRAINT `gopy_ibfk_1`
    FOREIGN KEY (`TaiKhoan`)
    REFERENCES `quanlybanlaptop`.`khachhang` (`TaiKhoan`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `quanlybanlaptop`.`phieuthu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlybanlaptop`.`phieuthu` (
  `SoPhieu` VARCHAR(30) NOT NULL,
  `NgayThu` DATE NULL DEFAULT NULL,
  `LyDo` VARCHAR(100) NULL DEFAULT NULL,
  `NgNop` VARCHAR(30) NULL DEFAULT NULL,
  `NgThu` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`SoPhieu`),
  INDEX `FK_7` (`NgNop` ASC),
  INDEX `FK_11` (`NgThu` ASC),
  CONSTRAINT `FK_11`
    FOREIGN KEY (`NgThu`)
    REFERENCES `quanlybanlaptop`.`nhanvien` (`MaNV`),
  CONSTRAINT `FK_7`
    FOREIGN KEY (`NgNop`)
    REFERENCES `quanlybanlaptop`.`khachhang` (`MaKH`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `quanlybanlaptop` ;

-- -----------------------------------------------------
-- Placeholder table for view `quanlybanlaptop`.`capnhatcthd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlybanlaptop`.`capnhatcthd` (`MaHD` INT, `TenHang` INT, `DonGia` INT, `SoLuong` INT, `ThanhTien` INT);

-- -----------------------------------------------------
-- Placeholder table for view `quanlybanlaptop`.`capnhatgiohang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlybanlaptop`.`capnhatgiohang` (`TaiKhoan` INT, `TenHang` INT, `MaHang` INT, `SoLuong` INT, `DonGia` INT, `ThanhTien` INT, `NgayMua` INT, `DiaChi` INT);

-- -----------------------------------------------------
-- Placeholder table for view `quanlybanlaptop`.`tonggiatrihoadon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlybanlaptop`.`tonggiatrihoadon` (`MaHD` INT, `TongTien` INT);

-- -----------------------------------------------------
-- View `quanlybanlaptop`.`capnhatcthd`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quanlybanlaptop`.`capnhatcthd`;
USE `quanlybanlaptop`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `quanlybanlaptop`.`capnhatcthd` AS select `quanlybanlaptop`.`cthoadon`.`MaHD` AS `MaHD`,`quanlybanlaptop`.`mathang`.`TenHang` AS `TenHang`,`quanlybanlaptop`.`mathang`.`DonGia` AS `DonGia`,`quanlybanlaptop`.`cthoadon`.`SoLuong` AS `SoLuong`,(`quanlybanlaptop`.`cthoadon`.`SoLuong` * `quanlybanlaptop`.`mathang`.`DonGia`) AS `ThanhTien` from (`quanlybanlaptop`.`cthoadon` join `quanlybanlaptop`.`mathang` on((`quanlybanlaptop`.`cthoadon`.`MaHang` = `quanlybanlaptop`.`mathang`.`MaHang`)));

-- -----------------------------------------------------
-- View `quanlybanlaptop`.`capnhatgiohang`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quanlybanlaptop`.`capnhatgiohang`;
USE `quanlybanlaptop`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `quanlybanlaptop`.`capnhatgiohang` AS select `quanlybanlaptop`.`giohang`.`TaiKhoan` AS `TaiKhoan`,`quanlybanlaptop`.`mathang`.`TenHang` AS `TenHang`,`quanlybanlaptop`.`giohang`.`MaHang` AS `MaHang`,`quanlybanlaptop`.`giohang`.`SoLuong` AS `SoLuong`,`quanlybanlaptop`.`mathang`.`DonGia` AS `DonGia`,(`quanlybanlaptop`.`mathang`.`DonGia` * `quanlybanlaptop`.`giohang`.`SoLuong`) AS `ThanhTien`,`quanlybanlaptop`.`giohang`.`NgayMua` AS `NgayMua`,`quanlybanlaptop`.`giohang`.`DiaChi` AS `DiaChi` from (`quanlybanlaptop`.`giohang` join `quanlybanlaptop`.`mathang` on((`quanlybanlaptop`.`giohang`.`MaHang` = `quanlybanlaptop`.`mathang`.`MaHang`)));

-- -----------------------------------------------------
-- View `quanlybanlaptop`.`tonggiatrihoadon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quanlybanlaptop`.`tonggiatrihoadon`;
USE `quanlybanlaptop`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `quanlybanlaptop`.`tonggiatrihoadon` AS select `capnhatcthd`.`MaHD` AS `MaHD`,sum(`capnhatcthd`.`ThanhTien`) AS `TongTien` from `quanlybanlaptop`.`capnhatcthd` group by `capnhatcthd`.`MaHD`;
USE `quanlybanlaptop`;

DELIMITER $$
USE `quanlybanlaptop`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `quanlybanlaptop`.`Update_TTTNV`
AFTER UPDATE ON `quanlybanlaptop`.`nhanvien`
FOR EACH ROW
begin
	
		update taikhoan 
        set SDT=new.SDT
        where TaiKhoan=NEW.TaiKhoan;
    END$$

USE `quanlybanlaptop`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `quanlybanlaptop`.`Update_TTTKH`
AFTER UPDATE ON `quanlybanlaptop`.`khachhang`
FOR EACH ROW
begin
	
		update taikhoan 
        set SDT=new.SDT
        where TaiKhoan=NEW.TaiKhoan;
    END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
